Add files via upload
boneIO-eu/boneIO pull request #74
Opened 2021-12-08 17:58 UTC by beliarti

2021-12-09 10:48 UTC, maciejkrasuski requested changes
Dorzuć, o ile to możliwe pliki źródłowe, jakby ktoś inny potrzebował zrobić analogiczną instrukcję dla kolejnych płytek. W końcu to projekt open source ;)

2021-12-09 16:54 UTC, beliarti commented
pliki z Corel Draw x18.

2021-12-14 20:12 UTC, maciejkrasuski requested changes
Hej,
Na opisać input board mamy takie błędy:
![image](https://user-images.githubusercontent.com/70077751/146071358-49ae649f-c21d-44b2-bc9a-db6c68ccf79f.png)

Wtyczka J14 - pomylona polaryzacja - gnd jest po prawej stronie. Nie jest to ADC więc najlepiej opisz to jako: EXT_PSU, a piny jako:
- +48V
- GND1

Wtyczka zasilania głównego powinna się nazywać VCC

Pin 8 na złączce J10 powinien się nazywać GND2

2021-12-17 15:45 UTC, beliarti commented
poprawiłem ale szału dostaje z tym gitem

2021-12-17 15:47 UTC, beliarti commented
poprawiłem ale nie wiem czy się zrobił upload

2021-12-19 00:36 UTC, maciejkrasuski requested changes
Jeszcze jedna prośba - usuń wszystkie etykiety z prefixem J (zarównoa na input jak i na relay). Niestety te złączki są autonumerowane i ciężko tu zachować kompatybilność wsteczną jak coś zmieniamy na płytkach. Po protu przesuń wszystko niżej a tamto wywal ;)

2023-05-30 07:10 UTC, closed without merging